/**
 * LexiQ - Word Bank & Clue Dictionary
 * Designed for a college AI Tools mini-project.
 * 
 * TARGET_WORDS: Curated recognizable 5-letter words paired with meaningful 
 *               clues used for the second hint.
 * VALID_GUESSES: Comprehensive set of allowed 5-letter English words.
 */

// Target words with semantic clues for Hint #2
const TARGET_WORDS = [
  { word: "APPLE", clue: "A popular crisp fruit that keeps the doctor away." },
  { word: "BRAVE", clue: "Showing courage when facing danger or adversity." },
  { word: "CHAIR", clue: "A piece of furniture designed for one person to sit on." },
  { word: "DANCE", clue: "Rhythmic movement of the body, usually to music." },
  { word: "EAGLE", clue: "A majestic bird of prey with powerful eyesight." },
  { word: "FLAME", clue: "The visible, gaseous part of a burning fire." },
  { word: "GRAPE", clue: "A small, juicy fruit that grows in clusters on vines." },
  { word: "HEART", clue: "An essential organ that pumps blood through the body." },
  { word: "IMAGE", clue: "A visual representation, photograph, or picture." },
  { word: "JUICE", clue: "The liquid naturally contained in fruit or vegetables." },
  { word: "KNIFE", clue: "A tool or weapon with a sharp edge used for cutting." },
  { word: "LEMON", clue: "A bright yellow citrus fruit known for its sour taste." },
  { word: "MUSIC", clue: "An art of sound in time that expresses ideas and emotions." },
  { word: "NIGHT", clue: "The period of darkness between sunset and sunrise." },
  { word: "OCEAN", clue: "A vast body of saltwater that covers most of Earth." },
  { word: "PIANO", clue: "A large musical instrument played using a keyboard of keys." },
  { word: "QUEEN", clue: "A female royal ruler or the wife of a king." },
  { word: "RIVER", clue: "A natural flowing watercourse heading toward an ocean or lake." },
  { word: "SMART", clue: "Showing quick-witted intelligence or clever thinking." },
  { word: "TRAIN", clue: "A series of connected railway cars pulled by a locomotive." },
  { word: "UNCLE", clue: "The brother of one's father or mother." },
  { word: "VOICE", clue: "The sound produced in a human larynx and uttered through mouth." },
  { word: "WATER", clue: "Transparent, tasteless liquid essential for all known life." },
  { word: "YOUTH", clue: "The period between childhood and adult age." },
  { word: "ZEBRA", clue: "An African wild horse with distinctive black-and-white stripes." },
  { word: "BREAD", clue: "Staple food made from baked flour and water dough." },
  { word: "CLOCK", clue: "An instrument to measure, keep, and indicate time." },
  { word: "DREAM", clue: "A series of thoughts and sensations occurring during sleep." },
  { word: "EARTH", clue: "Our home planet, third in distance from the sun." },
  { word: "FROST", clue: "A deposit of small white ice crystals formed on ground or windows." },
  { word: "GREEN", clue: "The color of living grass and emeralds." },
  { word: "HOUSE", clue: "A building for human habitation, especially one family." },
  { word: "LIGHT", clue: "Natural agent that stimulates sight and makes things visible." },
  { word: "MOUSE", clue: "A small rodent, or a handheld computer input device." },
  { word: "PLANT", clue: "A living organism that absorbs water and synthesizes nutrients." },
  { word: "ROBOT", clue: "A machine capable of carrying out complex actions automatically." },
  { word: "SHINE", clue: "To give out or reflect bright light." },
  { word: "TIGER", clue: "A large solitary cat with a yellow-brown coat with black stripes." },
  { word: "WORLD", clue: "The earth, together with all of its countries and peoples." },
  { word: "CLOUD", clue: "A visible mass of condensed water vapor floating in atmosphere." },
  { word: "BEACH", clue: "A pebbly or sandy shore by the ocean or a lake." },
  { word: "STORM", clue: "A violent disturbance of the atmosphere with strong winds and rain." },
  { word: "CANDY", clue: "A sweet confection made primarily with sugar or syrup." },
  { word: "PRIDE", clue: "A feeling of deep satisfaction from one's own achievements." },
  { word: "CHEST", clue: "Upper front part of the torso, or a sturdy wooden box." },
  { word: "STARS", clue: "Luminous celestial points visible in the clear night sky." },
  { word: "PEACE", clue: "Freedom from disturbance, tranquility, or cessation of war." },
  { word: "MAGIC", clue: "The power of apparently influencing events using mysterious forces." },
  { word: "SHARP", clue: "Having a fine edge or point capable of cutting or piercing." },
  { word: "SPACE", clue: "The physical universe beyond the earth's atmosphere." },
  { word: "SUGAR", clue: "A sweet crystalline substance obtained from sugar cane or beet." },
  { word: "TRACK", clue: "A rough path or trail, or rails for a train." },
  { word: "WATCH", clue: "A small timepiece worn typically on a strap on the wrist." },
  { word: "WHITE", clue: "The color of milk or fresh snow." },
  { word: "STONE", clue: "Hard solid non-metallic mineral matter of which rock is made." },
  { word: "TOWER", clue: "A tall, narrow building, either freestanding or part of a castle." },
  { word: "RADIO", clue: "Transmission and reception of sound messages via electromagnetic waves." },
  { word: "MONEY", clue: "Current medium of exchange in the form of coins and banknotes." },
  { word: "HORSE", clue: "A large domesticated mammal with hooves and a flowing mane." },
  { word: "GLASS", clue: "A hard, brittle transparent material used for windows and drinkware." }
];

// Additional valid guess words (to ensure natural gameplay and generous vocabulary)
const EXTRA_VALID_WORDS = [
  "ABOUT", "ABOVE", "ABUSE", "ACTOR", "ACUTE", "ADAPT", "ADMIT", "ADOPT", "ADULT", "AFTER",
  "AGAIN", "AGENT", "AGREE", "AHEAD", "ALARM", "ALBUM", "ALERT", "ALIKE", "ALIVE", "ALLOW",
  "ALONE", "ALONG", "ALTER", "AMONG", "ANGER", "ANGLE", "ANGRY", "APART", "APPLY", "ARENA",
  "ARGUE", "ARISE", "ARMED", "ARMOR", "ARROW", "ASIDE", "ASSET", "AUDIO", "AUDIT", "AVOID",
  "AWAIT", "AWAKE", "AWARD", "AWARE", "BADLY", "BAKER", "BASIC", "BASIS", "BEAST", "BEGIN",
  "BEING", "BELOW", "BENCH", "BIRTH", "BLACK", "BLAME", "BLANK", "BLAST", "BLEND", "BLESS",
  "BLIND", "BLOCK", "BLOOD", "BOARD", "BOAST", "BONUS", "BOOST", "BOUND", "BRAIN", "BRAND",
  "BRASS", "BREAK", "BRICK", "BRIDE", "BRIEF", "BRING", "BROAD", "BROWN", "BRUSH", "BUILD",
  "BUNCH", "BURST", "CABIN", "CABLE", "CANDY", "CARGO", "CARRY", "CATCH", "CAUSE", "CHAIN",
  "CHAMP", "CHANCE", "CHANG", "CHART", "CHASE", "CHEAP", "CHECK", "CHEEK", "CHEER", "CHIEF",
  "CHILD", "CHILL", "CHINA", "CHIPS", "CHOIR", "CHOSE", "CIVIC", "CIVIL", "CLAIM", "CLASS",
  "CLEAN", "CLEAR", "CLERK", "CLICK", "CLIFF", "CLIMB", "CLOAK", "CLONE", "CLOSE", "CLOTH",
  "COACH", "COAST", "COCOA", "COUCH", "COUNT", "COURT", "COVER", "CRACK", "CRAFT", "CRANE",
  "CRASH", "CRAZY", "CREAM", "CREEK", "CRIME", "CRISP", "CROSS", "CROWD", "CROWN", "CRUDE",
  "CRUEL", "CRUSH", "CYCLE", "DAILY", "DRAFT", "DRAIN", "DRAWN", "DRESS", "DRIFT", "DRILL",
  "DRINK", "DRIVE", "DROVE", "DYING", "EAGER", "EARLY", "EASEL", "EMPTY", "ENEMY", "ENJOY",
  "ENTER", "ENTRY", "EQUAL", "EQUIP", "ERROR", "ESSAY", "EVENT", "EVERY", "EXACT", "EXIST",
  "EXTRA", "FAINT", "FAITH", "FALSE", "FAULT", "FAVOR", "FEAST", "FIBER", "FIELD", "FIFTH",
  "FIFTY", "FIGHT", "FINAL", "FIRST", "FIXED", "FLASH", "FLEET", "FLOOR", "FLOUR", "FLUID",
  "FOCUS", "FORCE", "FORGE", "FORTH", "FORTY", "FORUM", "FOUND", "FRAME", "FRAUD", "FRESH",
  "FRONT", "FRUIT", "GIANT", "GIVEN", "GLOVE", "GRACE", "GRADE", "GRAND", "GRANT", "GRASP",
  "GREAT", "GRIEF", "GUEST", "GUIDE", "HABIT", "HAPPY", "HARSH", "HATCH", "HAVEN", "HEAVY",
  "HELLO", "HONEY", "HONOR", "HOTEL", "HUMAN", "HUMOR", "HURRY", "IDEAL", "INDEX", "INNER",
  "INPUT", "IRONY", "ISSUE", "JEWEL", "JOINT", "JUDGE", "LABEL", "LABOR", "LARGE", "LASER",
  "LATER", "LAUGH", "LAYER", "LEARN", "LEASE", "LEAST", "LEAVE", "LEGAL", "LEVEL", "LIMIT",
  "LINKS", "LOCAL", "LOGIC", "LOOSE", "LOVER", "LOWER", "LUCKY", "LUNCH", "MAJOR", "MAKER",
  "MARCH", "MATCH", "MAYBE", "MAYOR", "MEDIA", "METAL", "METER", "MIGHT", "MINOR", "MODEL",
  "MONTH", "MORAL", "MOTOR", "MOUNT", "NURSE", "OFFER", "ORDER", "OTHER", "OWNER", "PANEL",
  "PAPER", "PARTY", "PATCH", "PAUSE", "PHONE", "PHOTO", "PILOT", "PITCH", "PIVOT", "PLACE",
  "PLAIN", "PLANE", "PLATE", "POINT", "POUND", "POWER", "PRESS", "PRICE", "PRIME", "PRINT",
  "PRIZE", "PROOF", "PROUD", "PROVE", "PUPIL", "PUPPY", "PURSE", "QUICK", "QUIET", "QUITE",
  "RADIO", "RAISE", "RANGE", "RAPID", "RATIO", "REACH", "REACT", "READY", "REALM", "REBEL",
  "REFER", "RELAX", "REPLY", "RESET", "RIDER", "RIGHT", "RIVAL", "ROBIN", "ROUGH", "ROUND",
  "ROUTE", "ROYAL", "RULER", "RURAL", "SCALE", "SCENE", "SCOPE", "SCORE", "SENSE", "SERVE",
  "SHARE", "SHIFT", "SHIRT", "SHOCK", "SHOOT", "SIGHT", "SINCE", "SKILL", "SLATE", "SLEEP",
  "SLICE", "SLIDE", "SMILE", "SMOKE", "SOLID", "SOLVE", "SORRY", "SOUND", "SOUTH", "SPEED",
  "SPEND", "SPICE", "SPOKE", "SPORT", "STAGE", "STAND", "START", "STATE", "STEAM", "STEEL",
  "STICK", "STILL", "STOCK", "STORY", "STYLE", "SUITE", "SUPER", "SWEET", "SWIFT", "SWORD",
  "TABLE", "TASTE", "TEACH", "THEME", "THING", "THINK", "THIRD", "TIGHT", "TITLE", "TODAY",
  "TOPIC", "TOTAL", "TOUCH", "TOUGH", "TOWEL", "TRADE", "TRIAL", "TRIBE", "TRICK", "TRUCK",
  "TRULY", "TRUST", "TRUTH", "TWICE", "UNDER", "UNION", "UNITY", "UNTIL", "UPPER", "UPSET",
  "URBAN", "USAGE", "USUAL", "VALID", "VALUE", "VIDEO", "VIRUS", "VISIT", "VITAL", "VOTER",
  "WASTE", "WHEEL", "WHERE", "WHICH", "WHOLE", "WOMAN", "WOUND", "WRITE", "WRONG", "YIELD"
];

// Set of all valid guesses for fast O(1) lookup
const VALID_WORD_SET = new Set([
  ...TARGET_WORDS.map(item => item.word.toUpperCase()),
  ...EXTRA_VALID_WORDS.map(w => w.toUpperCase())
]);
