/**
 * LexiQ - Word Bank & Clue Dictionary
 * Designed for a college AI Tools mini-project.
 * 
 * TARGET_WORDS: Curated recognizable 5-letter words paired with meaningful 
 *               clues used for the second hint.
 * VALID_GUESSES: Comprehensive set of allowed 5-letter English words.
 */

// Target words with semantic clues for Hint #2
const TARGET_WORDS = [
  { word: "APPLE", clue: "A popular crisp fruit that keeps the doctor away." },
  { word: "BRAVE", clue: "Showing courage when facing danger or adversity." },
  { word: "CHAIR", clue: "A piece of furniture designed for one person to sit on." },
  { word: "DANCE", clue: "Rhythmic movement of the body, usually to music." },
  { word: "EAGLE", clue: "A majestic bird of prey with powerful eyesight." },
  { word: "FLAME", clue: "The visible, gaseous part of a burning fire." },
  { word: "GRAPE", clue: "A small, juicy fruit that grows in clusters on vines." },
  { word: "HEART", clue: "An essential organ that pumps blood through the body." },
  { word: "IMAGE", clue: "A visual representation, photograph, or picture." },
  { word: "JUICE", clue: "The liquid naturally contained in fruit or vegetables." },
  { word: "KNIFE", clue: "A tool or weapon with a sharp edge used for cutting." },
  { word: "LEMON", clue: "A bright yellow citrus fruit known for its sour taste." },
  { word: "MUSIC", clue: "An art of sound in time that expresses ideas and emotions." },
  { word: "NIGHT", clue: "The period of darkness between sunset and sunrise." },
  { word: "OCEAN", clue: "A vast body of saltwater that covers most of Earth." },
  { word: "PIANO", clue: "A large musical instrument played using a keyboard of keys." },
  { word: "QUEEN", clue: "A female royal ruler or the wife of a king." },
  { word: "RIVER", clue: "A natural flowing watercourse heading toward an ocean or lake." },
  { word: "SMART", clue: "Showing quick-witted intelligence or clever thinking." },
  { word: "TRAIN", clue: "A series of connected railway cars pulled by a locomotive." },
  { word: "UNCLE", clue: "The brother of one's father or mother." },
  { word: "VOICE", clue: "The sound produced in a human larynx and uttered through mouth." },
  { word: "WATER", clue: "Transparent, tasteless liquid essential for all known life." },
  { word: "YOUTH", clue: "The period between childhood and adult age." },
  { word: "ZEBRA", clue: "An African wild horse with distinctive black-and-white stripes." },
  { word: "BREAD", clue: "Staple food made from baked flour and water dough." },
  { word: "CLOCK", clue: "An instrument to measure, keep, and indicate time." },
  { word: "DREAM", clue: "A series of thoughts and sensations occurring during sleep." },
  { word: "EARTH", clue: "Our home planet, third in distance from the sun." },
  { word: "FROST", clue: "A deposit of small white ice crystals formed on ground or windows." },
  { word: "GREEN", clue: "The color of living grass and emeralds." },
  { word: "HOUSE", clue: "A building for human habitation, especially one family." },
  { word: "LIGHT", clue: "Natural agent that stimulates sight and makes things visible." },
  { word: "MOUSE", clue: "A small rodent, or a handheld computer input device." },
  { word: "PLANT", clue: "A living organism that absorbs water and synthesizes nutrients." },
  { word: "ROBOT", clue: "A machine capable of carrying out complex actions automatically." },
  { word: "SHINE", clue: "To give out or reflect bright light." },
  { word: "TIGER", clue: "A large solitary cat with a yellow-brown coat with black stripes." },
  { word: "WORLD", clue: "The earth, together with all of its countries and peoples." },
  { word: "CLOUD", clue: "A visible mass of condensed water vapor floating in atmosphere." },
  { word: "BEACH", clue: "A pebbly or sandy shore by the ocean or a lake." },
  { word: "STORM", clue: "A violent disturbance of the atmosphere with strong winds and rain." },
  { word: "CANDY", clue: "A sweet confection made primarily with sugar or syrup." },
  { word: "PRIDE", clue: "A feeling of deep satisfaction from one's own achievements." },
  { word: "CHEST", clue: "Upper front part of the torso, or a sturdy wooden box." },
  { word: "STARS", clue: "Luminous celestial points visible in the clear night sky." },
  { word: "PEACE", clue: "Freedom from disturbance, tranquility, or cessation of war." },
  { word: "MAGIC", clue: "The power of apparently influencing events using mysterious forces." },
  { word: "SHARP", clue: "Having a fine edge or point capable of cutting or piercing." },
  { word: "SPACE", clue: "The physical universe beyond the earth's atmosphere." },
  { word: "SUGAR", clue: "A sweet crystalline substance obtained from sugar cane or beet." },
  { word: "TRACK", clue: "A rough path or trail, or rails for a train." },
  { word: "WATCH", clue: "A small timepiece worn typically on a strap on the wrist." },
  { word: "WHITE", clue: "The color of milk or fresh snow." },
  { word: "ANGEL", clue: "A spiritual being often described as a messenger from heaven." },
  { word: "BEARD", clue: "Hair that grows on a person's chin and lower face." },
  { word: "BERRY", clue: "A small juicy fruit such as a strawberry or blueberry." },
  { word: "BLACK", clue: "The darkest color, produced by the absence of visible light." },
  { word: "BLANK", clue: "Containing nothing or having no information written on it." },
  { word: "BLAST", clue: "A powerful explosion or sudden strong burst of air." },
  { word: "BRAIN", clue: "The organ inside the head that controls thoughts and actions." },
  { word: "BRICK", clue: "A rectangular block commonly used for building walls." },
  { word: "BRUSH", clue: "An object with bristles used for cleaning, painting, or grooming." },
  { word: "CABLE", clue: "A thick wire used to carry electricity or signals." },
  { word: "CANDY", clue: "A sweet food usually made with sugar." },
  { word: "CARRY", clue: "To hold and move something from one place to another." },
  { word: "CATCH", clue: "To grab something that is moving through the air." },
  { word: "CLEAN", clue: "Free from dirt, marks, or unwanted substances." },
  { word: "CLEAR", clue: "Easy to see, understand, or recognize." },
  { word: "CRANE", clue: "A tall machine used to lift and move heavy objects." },
  { word: "CROWN", clue: "A decorative headpiece worn by a king or queen." },
  { word: "CYCLE", clue: "A bicycle or a series of events that repeats itself." },
  { word: "DAILY", clue: "Happening or done every day." },
  { word: "DEMON", clue: "An evil supernatural being in traditional stories." },
  { word: "DIARY", clue: "A book used for recording personal thoughts and daily events." },
  { word: "DREAM", clue: "A series of images and thoughts experienced while sleeping." },
  { word: "DRINK", clue: "A liquid that can be consumed." },
  { word: "DRIVE", clue: "To control and operate a vehicle." },
  { word: "EAGLE", clue: "A large bird of prey known for its powerful wings and sharp vision." },
  { word: "EARTH", clue: "The planet on which humans, animals, and plants live." },
  { word: "EMPTY", clue: "Containing nothing inside." },
  { word: "ENEMY", clue: "A person or group that is opposed to another." },
  { word: "ENJOY", clue: "To take pleasure or satisfaction in something." },
  { word: "EVENT", clue: "Something that happens, especially something planned or organized." },
  { word: "FAIRY", clue: "A magical imaginary creature often shown as small and winged." },
  { word: "FIELD", clue: "An open area of land, often used for farming or sports." },
  { word: "FIGHT", clue: "A physical struggle or conflict between people or groups." },
  { word: "FIRST", clue: "Coming before all others in time, order, or importance." },
  { word: "FLASH", clue: "A sudden brief burst of bright light." },
  { word: "FLOAT", clue: "To remain on the surface of a liquid without sinking." },
  { word: "FLOOR", clue: "The lower surface of a room that people walk on." },
  { word: "FOCUS", clue: "To give special attention to something." },
  { word: "FORCE", clue: "Strength or energy that can cause movement or change." },
  { word: "FRUIT", clue: "The edible part of many plants that usually contains seeds." },
  { word: "FUNNY", clue: "Causing laughter or amusement." },
  { word: "GIANT", clue: "A person or thing that is extremely large." },
  { word: "GHOST", clue: "The supposed spirit of a dead person." },
  { word: "GIANT", clue: "A person, animal, or object of unusually great size." },
  { word: "GLOVE", clue: "A covering worn on the hand to protect or warm it." },
  { word: "GRAIN", clue: "A small hard seed from crops such as wheat or rice." },
  { word: "GRASS", clue: "Green plants with narrow leaves that commonly cover fields and lawns." },
  { word: "GRILL", clue: "A device or surface used for cooking food over heat." },
  { word: "HAPPY", clue: "Feeling pleasure, joy, or satisfaction." },
  { word: "HONEY", clue: "A sweet golden substance produced by bees." },
  { word: "HORSE", clue: "A large four-legged animal commonly used for riding." },
  { word: "HOTEL", clue: "A building where people pay to stay for a short time." },
  { word: "HUMAN", clue: "A member of the species to which all modern people belong." },
  { word: "IDEAL", clue: "A standard or example considered perfect." },
  { word: "INNER", clue: "Situated inside or toward the center of something." },
  { word: "JEWEL", clue: "A precious stone used in decorative jewelry." },
  { word: "JOKER", clue: "A person who likes to make jokes or play tricks." },
  { word: "KINGS", clue: "Male rulers of kingdoms." },
  { word: "LARGE", clue: "Greater than average in size or amount." },
  { word: "LASER", clue: "A device that produces a narrow, powerful beam of light." },
  { word: "LEARN", clue: "To gain knowledge or skill through study or experience." },
  { word: "LEAVE", clue: "To go away from a place." },
  { word: "LEVEL", clue: "A position or height that is flat or equal." },
  { word: "LOCAL", clue: "Relating to a particular nearby place or area." },
  { word: "MAGIC", clue: "Mysterious power used to create seemingly impossible effects." },
  { word: "METAL", clue: "A hard material such as iron, copper, or gold." },
  { word: "MODEL", clue: "A representation of something used to show how it looks or works." },
  { word: "MONEY", clue: "Something commonly used to buy goods and services." },
  { word: "MONTH", clue: "One of the twelve divisions of a year." },
  { word: "MOTOR", clue: "A machine that converts energy into movement." },
  { word: "MOVIE", clue: "A recorded sequence of moving images that tells a story." },
  { word: "NERVE", clue: "A fiber that carries signals between the brain and the body." },
  { word: "NORTH", clue: "One of the four main directions on a compass." },
  { word: "NOVEL", clue: "A long fictional story written as a book." },
  { word: "OLIVE", clue: "A small fruit commonly used to produce cooking oil." },
  { word: "ORDER", clue: "A command or request telling someone to do something." },
  { word: "PAINT", clue: "A colored substance used to decorate or cover surfaces." },
  { word: "PAPER", clue: "A thin material commonly used for writing and printing." },
  { word: "PARTY", clue: "A social gathering held for celebration or entertainment." },
  { word: "PHONE", clue: "A device used to communicate with people over a distance." },
  { word: "PILOT", clue: "A person trained to operate an aircraft." },
  { word: "PLANE", clue: "An aircraft designed to fly through the air." },
  { word: "PLATE", clue: "A flat dish used for serving or eating food." },
  { word: "POINT", clue: "A particular place, position, or idea." },
  { word: "POWER", clue: "The ability or strength to do something." },
  { word: "QUEEN", clue: "A female monarch or the wife of a king." },
  { word: "QUIET", clue: "Making very little or no sound." },
  { word: "QUICK", clue: "Moving or happening at a high speed." },
  { word: "ROUND", clue: "Having a curved shape like a circle or sphere." },
  { word: "ROYAL", clue: "Relating to a king, queen, or royal family." },
  { word: "SCALE", clue: "A device used for measuring weight." },
  { word: "SHEEP", clue: "A wool-covered farm animal commonly raised for its fleece." },
  { word: "SHIRT", clue: "A piece of clothing worn on the upper part of the body." },
  { word: "SHOES", clue: "Items of footwear worn to protect the feet." },
  { word: "SKILL", clue: "The ability to do something well through practice or training." },
  { word: "SMILE", clue: "A facial expression showing happiness or friendliness." },
  { word: "SNAKE", clue: "A long, legless reptile with a flexible body." },
  { word: "SOUND", clue: "Something that can be heard." },
  { word: "SPEED", clue: "The rate at which something moves or happens." },
  { word: "SPORT", clue: "A physical activity or game played for competition or enjoyment." },
  { word: "SPOON", clue: "A utensil with a rounded bowl used for eating or serving." },
  { word: "SWEET", clue: "Having a pleasant taste like sugar or honey." },
  { word: "TABLE", clue: "A piece of furniture with a flat top and supporting legs." },
  { word: "TEACH", clue: "To help someone gain knowledge or learn a skill." },
  { word: "TEETH", clue: "Hard structures in the mouth used for biting and chewing." },
  { word: "THROW", clue: "To send something through the air using your hand." },
  { word: "TOUCH", clue: "To come into contact with something using the body." },
  { word: "TRADE", clue: "The activity of buying, selling, or exchanging goods." },
  { word: "TRUCK", clue: "A large road vehicle used for carrying goods." },
  { word: "TRUTH", clue: "The quality of being true or matching reality." },
  { word: "UNDER", clue: "In or toward a position below something else." },
  { word: "UNITY", clue: "The state of being joined together as one." },
  { word: "VALUE", clue: "The worth or importance of something." },
  { word: "VIDEO", clue: "A recording of moving images, usually with sound." },
  { word: "VIRUS", clue: "A tiny infectious agent that can cause disease." },
  { word: "WHEEL", clue: "A circular object that rotates around an axle." },
  { word: "WOMAN", clue: "An adult female human." },
  { word: "WORLD", clue: "The earth and all the people and places on it." },
  { word: "WRITE", clue: "To form letters or words using a pen, pencil, or keyboard." },
  { word: "YOUNG", clue: "Having lived for a relatively short time; not old." },
  { word: "ZONES", clue: "Areas that are separated or defined for a particular purpose." },
  { word: "STONE", clue: "Hard solid non-metallic mineral matter of which rock is made." },
  { word: "TOWER", clue: "A tall, narrow building, either freestanding or part of a castle." },
  { word: "RADIO", clue: "Transmission and reception of sound messages via electromagnetic waves." },
  { word: "MONEY", clue: "Current medium of exchange in the form of coins and banknotes." },
  { word: "HORSE", clue: "A large domesticated mammal with hooves and a flowing mane." },
  { word: "GLASS", clue: "A hard, brittle transparent material used for windows and drinkware." }
];

// Additional valid guess words (to ensure natural gameplay and generous vocabulary)
const MORE_VALID_WORDS = [

  "ABOVE", "ADORE", "ADULT", "AISLE", "ALERT", "ALIEN", "ALIVE", "AMBER", "AMUSE", "ANGEL",
  "ANKLE", "APPLE", "ARENA", "ARISE", "ARROW", "ASIDE", "ASSET", "AUDIO", "AWARD", "BADGE",

  "BOXER", "BRAIN", "BRAND", "BRAVE", "BREAD", "BREAK", "BRIDE", "BRING", "BROAD", "BROKE",

  "BAKER", "BASIC", "BEACH", "BEARD", "BEAST", "BEGIN", "BELLY", "BENCH", "BERRY", "BIRTH",
  "BLADE", "BLAME", "BLIND", "BLISS", "BLOOM", "BOARD", "BOAST", "BONUS", "BOUND", "BRAIN",

  "BRAVE", "BREAD", "BREAK", "BRIDE", "BRING", "BROAD", "BROKE", "BROOK", "BROWN", "BURST",
  "CABIN", "CABLE", "CAMEO", "CARGO", "CAUSE", "CEDAR", "CHAIN", "CHAIR", "CHALK", "CHARM",

  "CHEAP", "CHEER", "CHEST", "CHIEF", "CHILD", "CHOIR", "CIVIC", "CLOUD", "CLOAK", "CLOCK",
  "CLOSE", "CLOWN", "COACH", "COAST", "COLOR", "COMET", "CORAL", "CORNER", "COUGH", "COUNT",

  "COURT", "COVER", "CRANE", "CRISP", "CROWN", "CRUSH", "DAILY", "DANCE", "DEATH", "DELAY",
  "DEPTH", "DIARY", "DIRTY", "DOUBT", "DOZEN", "DREAM", "DRINK", "DRIVE", "EARTH", "EIGHT",

  "ELBOW", "ELDER", "EMPTY", "ENJOY", "ENTER", "EQUAL", "ERROR", "ESSAY", "EVENT", "EXACT",
  "FAIRY", "FAITH", "FALSE", "FANCY", "FEAST", "FENCE", "FERRY", "FINAL", "FLAME", "FLASH",

  "FLEET", "FLOOR", "FLOUR", "FLUTE", "FOCUS", "FORCE", "FORTH", "FRAME", "FRESH", "FRONT",
  "FROST", "FRUIT", "FUNNY", "GIANT", "GHOST", "GLASS", "GLOBE", "GLORY", "GRACE", "GRADE",

  "GRAND", "GRAPE", "GRASS", "GRILL", "GROUP", "GUARD", "GUEST", "GUIDE", "HABIT", "HAPPY",
  "HEART", "HEAVY", "HELLO", "HONEY", "HORSE", "HOUSE", "HUMAN", "HUMOR", "IMAGE", "INDEX",

  "INNER", "INPUT", "IRONY", "ISSUE", "JEWEL", "JOKER", "JUICE", "KNIFE", "LABEL", "LASER",
  "LAUGH", "LEMON", "LIGHT", "LIMIT", "LOCAL", "LOGIC", "LOVER", "LUCKY", "LUNCH", "MAGIC",

  "MAJOR", "MAKER", "MANGO", "MATCH", "MAYBE", "METAL", "MIGHT", "MINOR", "MOUSE", "MOVIE",
  "MUSIC", "NERVE", "NIGHT", "NOBLE", "NORTH", "NOVEL", "OCEAN", "OFFER", "OLIVE", "OPERA",

  "ORDER", "OWNER", "PAINT", "PANEL", "PEACE", "PEACH", "PEARL", "PIANO", "PILOT", "PIZZA",
  "PLANT", "PLATE", "POUND", "PRIDE", "PRIZE", "PROUD", "PUPPY", "PURSE", "QUEEN", "QUIET",

  "QUICK", "RADIO", "RAISE", "RANGE", "READY", "REBEL", "REPLY", "RIVER", "ROBIN", "ROBOT",
  "ROUGH", "ROUND", "ROYAL", "RULER", "SAUCE", "SCALE", "SCENE", "SHEEP", "SHINE", "SHOCK",

  "SHOES", "SHORE", "SHORT", "SIGHT", "SKATE", "SKILL", "SMILE", "SMOKE", "SNAKE", "SOLID",
  "SPACE", "SPEAK", "SPEED", "SPOON", "STAGE", "STARS", "STONE", "STORM", "STYLE", "SUGAR",

  "TABLE", "TASTE", "TEETH", "THEME", "THINK", "THROW", "TIGER", "TITLE", "TODAY", "TOWER",
  "TRACK", "TRAIN", "TRUST", "TRUTH", "UNCLE", "UNDER", "UNITY", "UPPER", "VALUE", "VIDEO",

  "VITAL", "VOICE", "WATER", "WATCH", "WHEEL", "WHITE", "WHOLE", "WOMAN", "WORLD", "WRITE",
  "YOUTH", "ZEBRA"

];


// Set of all valid guesses for fast O(1) lookup
const VALID_WORD_SET = new Set([
  ...TARGET_WORDS.map(item => item.word.toUpperCase()),
  ...MORE_VALID_WORDS.map(w => w.toUpperCase())
]);